### ISSUE TITLE
jensaarai:eval-multi-line keymap error "range.serialize is not a function"

### ISSUE THREAD

**Issue by lwlsn** [shawnlawson/jensaarai#1]
"cmd-enter": "jensaarai:eval-multi-line" keymap from throws the above error. 

From : .atom/packages/jensaarai/lib/text-recording.js:117

**Comment by shawnlawson** [comment]
OK, I think I tracked this down. I'm not sure why line and block are different, seems like they're both passing back an Atom Range object. Although it seems like Atom v1.51 has a getCurrentParagraphBufferRange() function that returns a proper Range that can be serialized; whereas I was previously doing this manually. I'll push the change into 0.2.7.
